### ISSUE TITLE
phpmetrics command with error

### ISSUE THREAD

**Issue by omrqs** [jakzal/phpqa#311]
```
Warning: Undefined array key 314 in phar:///tools/.phive/phars/phpmetrics/phpmetrics-2.7.3.phar/vendor/nikic/php-parser/lib/PhpParser/Lexer.php on line 293

Fatal error: Uncaught TypeError: PhpParser\Lexer::getNextToken(): Return value must be of type int, null returned in phar:///tools/.phive/phars/phpmetrics/phpmetrics-2.7.3.phar/vendor/nikic/php-parser/lib/PhpParser/Lexer.php:333
Stack trace:
#0 phar:///tools/.phive/phars/phpmetrics/phpmetrics-2.7.3.phar/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(208): PhpParser\Lexer->getNextToken('Symfony\\Bundle\\...', Array, Array)
#1 phar:///tools/.phive/phars/phpmetrics/phpmetrics-2.7.3.phar/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(158): PhpParser\ParserAbstract->doParse()
#2 phar:///tools/.phive/phars/phpmetrics/phpmetrics-2.7.3.phar/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(51): PhpParser\ParserAbstract->parse('<?php\n\ndeclare(...', Object(PhpParser\ErrorHandler\Throwing))
#3 phar:///tools/.phive/phars/phpmetrics/phpmetrics-2.7.3.phar/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(32): PhpParser\Parser\Multiple->tryParse(Object(PhpParser\Parser\Php7), Object(PhpParser\ErrorHandler\Throwing), '<?php\n\ndeclare(...')
#4 phar:///tools/.phive/phars/phpmetrics/phpmetrics-2.7.3.phar/src/Hal/Application/Analyze.php(104): PhpParser\Parser\Multiple->parse('<?php\n\ndeclare(...')
#5 phar:///tools/.phive/phars/phpmetrics/phpmetrics-2.7.3.phar/src/Hal/Application/Application.php(57): Hal\Application\Analyze->run(Array)
#6 /tools/.phive/phars/phpmetrics/phpmetrics-2.7.3.phar(22): Hal\Application\Application->run(Array)
#7 {main}
  thrown in phar:///tools/.phive/phars/phpmetrics/phpmetrics-2.7.3.phar/vendor/nikic/php-parser/lib/PhpParser/Lexer.php on line 333
```

**Comment by jakzal** [comment]
How did you run phpmetrics? What arguments/options have you used?

Which phpqa image have you tried?

**Comment by ToGo101** [comment]
i have the same issue, this is what i run:
```
  php-metrics:
    image: jakzal/phpqa:php8.0
    volumes:
      - ./:/project
    command: phpmetrics /project --report-html=./metrics/report --exclude=tests,vendor,var,.docker
```

**Comment by jakzal** [comment]
This seems to be a problem with phpmetrics. See https://github.com/phpmetrics/PhpMetrics/issues/459

**Comment by siemendev** [comment]
Hi folks!
I recently stumbled across this issue as well. It looks like this is a problem with php8, downgrading my phpmetrics pipeline to 7.4 solved the issue so at least there's a workaround for users experiencing this.
I guess there's still some work to do to be php8 compatible.
