### ISSUE TITLE
phan - php8.1 versus latest

### ISSUE THREAD

**Issue by cavo789** [jakzal/phpqa#377]
Hello

I was running the following command and get an error. 

```bash
docker run -it --rm -v $(pwd):/project -w /project -u 1000:1000 jakzal/phpqa:php8.1 phan --config-file=.config/phan.php
```

```text
ERROR: AssertionError: The pcntl extension must be loaded in order for Phan to be able to fork. in phar:///tools/.phive/phars/phan-5.4.0.phar/src/Phan/Phan.php:239
Stack trace:
#0 phar:///tools/.phive/phars/phan-5.4.0.phar/src/phan.php(38): Phan\Phan::analyzeFileList(Object(Phan\CodeBase), Object(Closure))
#1 /tools/.phive/phars/phan-5.4.0.phar(6): require('phar:///tools/....')
#2 {main}
(Phan 5.4.0 crashed due to an uncaught Throwable)
More details:
#0: Phan\Phan::analyzeFileList() called at [phar:///tools/.phive/phars/phan-5.4.0.phar/src/phan.php:38] Args: [Phan\CodeBase({}), Closure]
#1: require() called at [/tools/.phive/phars/phan-5.4.0.phar:6] Args: ["phar:///tools/.phive/phars/phan-5.4.0.phar/src/phan.php"]
```

This didn't happens when running phpqa:latest like this:

```bash
docker run -it --rm -v $(pwd):/project -w /project -u 1000:1000 jakzal/phpqa:latest phan --config-file=.config/phan.php
```

Can you advice me: I'm wish to run PHAN against php 8.1 codebase, should I use `jakzal/phpqa:php8.1` or the latest version?  I'm not sure to know when to use latest and when a dedicated one.

Thanks

**Comment by jakzal** [comment]
Did you pull the latest version of php8.1 tag with docker pull?

can you please make sure you have the latest build of both `latest` and `php8.1` and report back if the problem persists?

**Comment by cavo789** [comment]
Thanks for the quick reply.

I've always thought that Docker will always check if the version used is the latest one (with the correct tag). So running `docker run xxxx  jakzal/phpqa:php8.1` implicitly ask Docker to check if `jakzal/phpqa:php8.1` is up-to-date. Is this wrong?

I've neverthless manually make a `docker pull`:

```text
❯ docker pull jakzal/phpqa:php8.1
php8.1: Pulling from jakzal/phpqa
Digest: sha256:2815e8c9ac67ce658567cc560941873d485dd04a9f9b0f0b6d620cce32db21b9
Status: Image is up to date for jakzal/phpqa:php8.1
docker.io/jakzal/phpqa:php8.1
```

And, without surprise (since no update), same result:

```text
❯ docker run -it --rm -v $(pwd):/project -w /project -u 1000:1000 jakzal/phpqa:php8.1 phan --config-file=.config/phan.php
ERROR: AssertionError: The pcntl extension must be loaded in order for Phan to be able to fork. in phar:///tools/.phive/phars/phan-5.4.0.phar/src/Phan/Phan.php:239
Stack trace:
#0 phar:///tools/.phive/phars/phan-5.4.0.phar/src/phan.php(38): Phan\Phan::analyzeFileList(Object(Phan\CodeBase), Object(Closure))
#1 /tools/.phive/phars/phan-5.4.0.phar(6): require('phar:///tools/....')
#2 {main}
(Phan 5.4.0 crashed due to an uncaught Throwable)
More details:
#0: Phan\Phan::analyzeFileList() called at [phar:///tools/.phive/phars/phan-5.4.0.phar/src/phan.php:38] Args: [Phan\CodeBase({}), Closure]
#1: require() called at [/tools/.phive/phars/phan-5.4.0.phar:6] Args: ["phar:///tools/.phive/phars/phan-5.4.0.phar/src/phan.php"]
```

As said, I don't have this issue with 

```bash
docker run -it --rm -v $(pwd):/project -w /project -u 1000:1000 jakzal/phpqa:latest phan --config-file=.config/phan.php
```

Thanks

**Comment by cavo789** [comment]
Ok, sorry, only fired docker pull for 8.1.  Now with latest and 1. you're right about the "automatic docker pull" (I've learned something) 2. the error is there too.

```text
❯ docker pull jakzal/phpqa:latest
latest: Pulling from jakzal/phpqa
Digest: sha256:2815e8c9ac67ce658567cc560941873d485dd04a9f9b0f0b6d620cce32db21b9
Status: Downloaded newer image for jakzal/phpqa:latest
docker.io/jakzal/phpqa:latest
❯ docker run -it --rm -v $(pwd):/project -w /project -u 1000:1000 jakzal/phpqa:latest phan --config-file=.config/phan.php
ERROR: AssertionError: The pcntl extension must be loaded in order for Phan to be able to fork. in phar:///tools/.phive/phars/phan-5.4.0.phar/src/Phan/Phan.php:239
Stack trace:
#0 phar:///tools/.phive/phars/phan-5.4.0.phar/src/phan.php(38): Phan\Phan::analyzeFileList(Object(Phan\CodeBase), Object(Closure))
#1 /tools/.phive/phars/phan-5.4.0.phar(6): require('phar:///tools/....')
#2 {main}
(Phan 5.4.0 crashed due to an uncaught Throwable)
More details:
#0: Phan\Phan::analyzeFileList() called at [phar:///tools/.phive/phars/phan-5.4.0.phar/src/phan.php:38] Args: [Phan\CodeBase({}), Closure]
#1: require() called at [/tools/.phive/phars/phan-5.4.0.phar:6] Args: ["phar:///tools/.phive/phars/phan-5.4.0.phar/src/phan.php"]
```

**Comment by jakzal** [comment]
Thanks. Looks like the recent merge of https://github.com/jakzal/phpqa/pull/371 broke some things.

I’ll have a look at fixing or reverting the change. In the meantime you can use the latest tagged version that’s immutable (i.e. `1.77.2-php8.1`).

**Comment by ciaranmcnulty** [comment]
Yeah you need `--pull` to 'always pull the latest'

**Comment by cavo789** [comment]
Thanks for the tip @ciaranmcnulty

**Comment by cavo789** [comment]
>In the meantime you can use the latest tagged version that’s immutable (i.e. `1.77.2-php8.1`).

I confirm, it's working back with `1.77.2-php8.1`.

**Comment by jakzal** [comment]
@cavo789 Ciaran has added the missing extension back in https://github.com/jakzal/phpqa/pull/378

All the mutable images were now rebuilt. Can you try again and report if the problem is fixed for you? Thanks!

**Comment by cavo789** [comment]
Good morning @jakzal and @ciaranmcnulty 

I confirm, it's back as it should. Many thanks for the very quick solution.

💯
